const AppConstants = {
	FILTER_PEOPLE: 'FILTER_PEOPLE',
	FILTER_CATEGORIES: 'FILTER_CATEGORIES',
	FILTER_DOMAINS: 'FILTER_DOMAINS',
	FILTER_SENT: 'FILTER_SENT',
	FILTER_RECEIVED: 'FILTER_RECEIVED',
	FILTER_ALL: 'FILTER_ALL',
	FILTER_STARRED: 'FILTER_STARRED',

	ADD_MESSAGE: 'ADD_MESSAGE',
	REMOVE_MESSAGE: 'REMOVE_MESSAGE',
	FAVORITE_MESSAGE: 'FAVORITE_MESSAGE',

	FETCH_MESSAGES: 'FETCH_MESSAGES',
	FETCH_FILTERS:  'FETCH_FILTERS',
	FETCH_CATEGORIES: 'FETCH_CATEGORIES', 

	LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
	LOGIN_FAILED: 'LOGIN_FAILED',

	tabNames: {
		ALL: 'ALL',
		SENT: 'SENT',
		RECEIVED: 'RECEIVED',		
		STARRED: 'STARRED'
	}
};

export default AppConstants;