const appConstants = {
	FILTER_PEOPLE: 'FILTER_PEOPLE',
	FILTER_CATEGORIES: 'FILTER_CATEGORIES',
	FILTER_DOMAINS: 'FILTER_DOMAINS',
	FILTER_SENT: 'FILTER_SENT',
	FILTER_RECEIVED: 'FILTER_RECEIVED',
	FILTER_ALL: 'FILTER_ALL',

	ADD_MESSAGE: 'ADD_MESSAGE',
	REMOVE_MESSAGE: 'REMOVE_MESSAGE',

	FETCH_MESSAGES: 'FETCH_MESSAGES',
	FETCH_FILTERS:  'FETCH_FILTERS',

	LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
	LOGIN_FAILED: 'LOGIN_FAILED'
};

export default appConstants;